config/routes.rb
WinterCards::Application.routes.draw do
  root to: 'home#index'

  post 'set_language', to: 'home#set_language'
  get 'ajax/add_to_basket', to: 'home#add_to_basket'
  get 'ajax/remove_from_basket', to: 'home#remove_from_basket'
  get 'ajax/basket_data', to: 'home#basket_data'
  get 'ajax/clear_basket', to: 'home#clear_basket'

  get '/cart',to: 'home#cart'

  get '/iwantthiscards' => 'deals#new'
  resources :deals, only: [:new , :create, :show], model: 'deal', path: 'checkout'


  get 'admin' => 'admin#index'

  namespace :admin do
    get 'deals', to: 'deals#index'
    delete 'destroy_deal'

    get 'show_deal'
    post 'checkout_deal'
    resources :cards, model: 'card', except: :show
  end

end

app/views/admin/_search.html.slim
= simple_form_for '', method: :get do |form|
  = form.input :term, required: false, label: 'Код заказа: '
  = form.submit 'Найти'

app/views/admin/index.html.slim
div.container
  = render 'search'
  table.table.table-striped
    tr
      td Полное имя
      td Страна
      td Время
      td Код заказа
      td Статус
      td
        | Цена покупки \ цена за почту (ls)
      td Удалить
    - @deals.each do |deal|
      tr
        td
          = link_to deal.full_name, admin_show_deal_path(id: deal.id)
        td = deal.country
        td
          = time_tag deal.created_at
        td = deal.deal_number
        td
          = link_to admin_checkout_deal_path(id: deal.id), method: :post, remote: true, class: 'checkout-status' do
            - if !deal.checked
              span.label.label-danger не обработан
            - else
              span.label.label-success обработан
        td
          = "Ls:#{deal.deal_price} || #{deal.mail_price}"
        td
          = link_to 'DESTROY', admin_destroy_deal_path(deal_id: deal.id), class: 'btn btn-danger', method: :delete, :confirm => 'Это точно неважная хрень?'

- content_for :javascript do
  javascript:
    $(function(){

      $('.checkout-status').on('ajax:success',function(event, xhr, settings){
        if (xhr.update == false)
          $(this).find('span').removeClass('label-success').addClass('label-danger').text('не обработан');
        else
          $(this).find('span').removeClass('label-danger').addClass('label-success').text('обработан');
      });
    });

app/views/admin/show_deal.html.slim
div.container
  table.table.table-striped
    tr
      td Полное имя
      td = @deal.full_name
    tr
      td Эмайл
      td
        = mail_to @deal.email, @deal.email
    tr
      td Тел. номер
      td = @deal.tel_number
    tr
      td Страна
      td = @deal.country.capitalize
    tr
      td Город
      td = @deal.city.capitalize
    tr
      td Улица
      td = @deal.street
    tr
      td Почтовый индекс
      td = @deal.index
    tr
      td Комент к заказу
      td = @deal.comment
    tr
      td Номер сделки
      td = @deal.deal_number
    tr
      td Статус
      td
        = link_to admin_checkout_deal_path(id: @deal.id), method: :post, remote: true, id: 'checkout-status' do
          - if !@deal.checked
            span.label.label-danger не обработан
          - else
            span.label.label-success обработан
    tr
      td Заказанные изображения
      td
        ul.images
          - @deal.ordered_cards.each do |card|
            - next if card[1] == 0
            li
              = image_tag image_url("cards/preview/card_#{card[0][-1, 1]}_demo.png")
              span
                = card[1]

  = link_to 'back', :back
- content_for :javascript do
  javascript:
    $(function(){

      $(window).on('ajaxSuccess', function(event, xhr, settings){
        if (xhr.responseJSON.update == false)
          $('#checkout-status > span').removeClass('label-success').addClass('label-danger').text('не обработан');
        else
          $('#checkout-status > span').removeClass('label-danger').addClass('label-success').text('обработан');
      });
    });