config/routes.rb
WinterCards::Application.routes.draw do
  root to: 'home#index'

  post 'set_language', to: 'home#set_language'
  get 'ajax/add_to_basket', to: 'home#add_to_basket'
  get 'ajax/remove_from_basket', to: 'home#remove_from_basket'
  get 'ajax/basket_data', to: 'home#basket_data'
  get 'ajax/clear_basket', to: 'home#clear_basket'

  get '/cart',to: 'home#cart'

  get '/iwantthiscards' => 'deals#new'
  resources :deals, only: [:new , :create, :show], model: 'deal', path: 'checkout'


  get 'admin' => 'admin#index'

  namespace :admin do
    get 'deals', to: 'deals#index'
    delete 'destroy_deal'

    get 'show_deal'
    post 'checkout_deal'
    resources :cards, model: 'card', except: :show
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include ActionView::Helpers::NumberHelper
  include ApplicationHelper

  def index
  end

  def add_to_basket
    count = add_to_basket_one_card params[:card_id]
    total_cards_price_text = current_price_for_bucket
    total_mail_price_text = current_mail_price
    render json: { count: count, total_price_text: total_cards_price_text , mail_price_text: total_mail_price_text}, status: :ok
  end

  def remove_from_basket
    count = remove_from_basket_one_card params[:card_id]
    total_cards_price_text = current_price_for_bucket
    total_mail_price_text = current_mail_price
    render json: { count: count, total_price_text: total_cards_price_text , mail_price_text: total_mail_price_text}, status: :ok
  end


  def set_language
    if params[:language] == 'rus' || params[:language] == 'lv'
      session[:current_language] = params[:language]
    end
    render nothing: true, status: 200
  end


  private

    def cart_params
      params.require(:cart).permit :count, :card_id
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_envelope.html.slim
- show_link_to_deal ||= false
section.envelope
  = image_tag image_url('envelope2.png')
  ul.count_menu id="card1-count-menu"
    li.dec
      = link_to '-', ajax_remove_from_basket_path(card_id: 'card1'), remote: true
    li.count
      = count_of_specify_card 'card1'
    li.inc
      = link_to '+', ajax_add_to_basket_path(card_id: 'card1'), remote: true

  ul.count_menu id="card2-count-menu"
    li.dec
      = link_to '-', ajax_remove_from_basket_path(card_id: 'card2'), remote: true
    li.count
      = count_of_specify_card 'card2'
    li.inc
      = link_to '+', ajax_add_to_basket_path(card_id: 'card2'), remote: true

  ul.count_menu id="card3-count-menu"
    li.dec
      = link_to '-', ajax_remove_from_basket_path(card_id: 'card3'), remote: true
    li.count
      = count_of_specify_card 'card3'
    li.inc
      = link_to '+', ajax_add_to_basket_path(card_id: 'card3'), remote: true

  h3
    = t 'summ'
    | &nbsp
    span id="total-price"
      = current_price_for_bucket
    span.delivery-payment
      = t 'delivery'
      | &nbsp
      span.blue-summ-text id="total-mail-price"
        = current_mail_price
  - if show_link_to_deal
    = link_to t('go_to_text'), iwantthiscards_path, class: 'btn'
    h2 = t 'payment_by_bank'

- content_for :javascript do
  javascript:
    var $cardsMenu = [{
      count: $('#card1-count-menu > li.count').text(),
      body: $('#card1-count-menu'),
      counter:  $('#card1-count-menu > li.count')
    },{
      count: $('#card2-count-menu > li.count').text(),
      body: $('#card2-count-menu'),
      counter:  $('#card2-count-menu > li.count')
    },{
      count: $('#card3-count-menu > li.count').text(),
      body: $('#card3-count-menu'),
      counter:  $('#card3-count-menu > li.count')
    }];
    $totalPrices = {
      mail_price: $('#total-mail-price'),
      total_price: $('#total-price')
    };

    $(window).ready(function (){
      $.each( $cardsMenu, function (index, value){
        value.body.on('ajax:success', function (event, request, settings){
          value.counter.text(request.count);
          $totalPrices.mail_price.text(request.mail_price_text);
          $totalPrices.total_price.text(request.total_price_text);
        });

      });

    });

app/views/home/cart.html.slim
/ ul
/   - @cards.each do |card|
/     li 
/       = image_tag card[0].image.url
/       = card[0].title
/       = card[0].description
/       = link_to "delete from cart", delete_from_cart_path(card_id: card[0].identifier), remote: true, method: :post
/       br
/       = card[1]

section.home
  ul
    - @cards.each do |card|
      li
        = link_to card[0].image.url, title: card[0].title, class: 'fancybox' do
          = image_tag card[0].image.url
        = link_to "delete from cart", delete_from_cart_path(card_id: card[0].identifier), method: :post, class: "delete-from-cart"

app/views/home/index.html.slim
section.content.hidden
  section.home
    header
      section.logo style="background: url('#{image_url('logo_' + I18n.locale.to_s + '.png')}') no-repeat;"
    div.languages
      = link_to 'LV', set_language_path(language: 'lv'), method: :post, remote: true
      =<> link_to 'РУС', set_language_path(language: 'rus'), method: :post, remote: true
    ul.cards
      li
        = link_to image_url('cards/preview/card_1_demo.png'), class: 'fancybox' do
          = image_tag image_url('cards/board/card_1.png')
      li
        = link_to image_url('cards/preview/card_2_demo.png'), class: 'fancybox' do
          = image_tag image_url('cards/board/card_2.png')
      li
        = link_to image_url('cards/preview/card_3_demo.png'), class: 'fancybox' do
          = image_tag image_url('cards/board/card_3.png')

    ul.add-buttons
      li
        = link_to t('to_envelope'), ajax_add_to_basket_path(card_id: 'card1'), class: 'to-envelope', id:"card1_to_basket", remote: true
      li
        = link_to t('to_envelope'), ajax_add_to_basket_path(card_id: 'card2'), class: 'to-envelope', id:"card2_to_basket", remote: true
      li
        = link_to t('to_envelope'), ajax_add_to_basket_path(card_id: 'card3'), class: 'to-envelope', id:"card3_to_basket", remote: true

    figure.shelf

    aside
      dl
        dt = t 'pricing'
        dd
          span = "#{t('one_card')}............Ls0.80/€1.14"
          span = "#{t('three_cards')}.............Ls2.10/€2.98"
          span = "#{t('nine_cards')}........Ls6.15/€8.73"

        dt = t'about_cards'
        dd
          span = t 'size'
          span = t 'material'

          span = t 'made_in_latvia'

        dt = t 'artists'
        dd
          = link_to t('dmitry'), 'http://dmitri.ivi.lv', target: '_blank'
          = link_to t('tom'), 'http://tomsvfx.blogspot.com', target: '_blank'
          = link_to t('anna'), 'http://www.behance.net/annakislitsona', target: '_blank'
          = link_to t('nikita'), 'http://www.flickr.com/photos/76969646@N08/', target: '_blank'

    section.content
      = render 'envelope', show_link_to_deal: true

    div.clearfix
    h2
      = t 'if_you_want_to_place.first'
      =<> mail_to 'dmitri@ivi.lv', 'dmitri@ivi.lv'
      = t 'if_you_want_to_place.last'
footer
  figure
  figure.big
  section.content
    | &copy;SIA &laquo;Pamplemouse&raquo; 2013
    /p Также открытки можно приобрести в Даугавпилсе, в т/ц Ditton Nams 14.v.69., Cietokšņa iela 60 (напротив эскалатора).

- content_for :javascript do
  javascript:
    $(function () {
      $cardsButtons = {
        card1Button: $('#card1_to_basket'),
        card2Button: $('#card2_to_basket'),
        card3Button: $('#card3_to_basket'),
      };
      $counters = {
        'card1Button': $('#card1-count-menu > li.count'),
        'card2Button': $('#card2-count-menu > li.count'),
        'card3Button': $('#card3-count-menu > li.count')
      };
      $.each( $cardsButtons, function ( index, value){
        value.on('ajax:success', function(event, request, settings){
          $counters[index].text(request.count);
          $totalPrices.mail_price.text(request.mail_price_text);
          $totalPrices.total_price.text(request.total_price_text);
        });
      });
    });