config/routes.rb
WinterCards::Application.routes.draw do
  root to: 'home#index'

  post 'set_language', to: 'home#set_language'
  get 'ajax/add_to_basket', to: 'home#add_to_basket'
  get 'ajax/remove_from_basket', to: 'home#remove_from_basket'
  get 'ajax/basket_data', to: 'home#basket_data'
  get 'ajax/clear_basket', to: 'home#clear_basket'

  get '/cart',to: 'home#cart'

  get '/iwantthiscards' => 'deals#new'
  resources :deals, only: [:new , :create, :show], model: 'deal', path: 'checkout'


  get 'admin' => 'admin#index'

  namespace :admin do
    get 'deals', to: 'deals#index'
    delete 'destroy_deal'

    get 'show_deal'
    post 'checkout_deal'
    resources :cards, model: 'card', except: :show
  end

end

app/models/card.rb
class Card
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Paperclip

  has_mongoid_attached_file :image,format: :png
  
  has_and_belongs_to_many :deals

  field :title, type: String
  field :description, type: String
  field :price, type: Integer
  field :identifier, type: String
  index identifier: 1

  belongs_to :deal

  before_save :generate_code


  def to_param
  	self.identifier.to_s
  end

  public
    def generate_code
      if self.identifier.blank?
        self.identifier = SecureRandom.hex(2)
        generate_code if Card.where(identifier: self.identifier).present?
      end
    end

    def self.cards_in_bucket(session)
      cards = Card.all
      bucket = []
      cards.each do |card|
        bucket << {id: card.id.to_s, image_url: card.image.url.to_s, count: session[card.id], card: card} if !session[card.id].nil?
      end
      bucket
    end

end

app/controllers/admin/cards_controller.rb
class Admin::CardsController < AdminController
  before_action :get_card, except: [:new, :index]
  def index
    @cards = Card.all.desc :created_at
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new card_param
    if @card.save
      redirect_to admin_cards_path
    else
      render action: 'new'
    end
  end

  def update
    if @card.update_attributes card_param 
      redirect_to admin_cards_path
    else
      render action: 'edit'
    end
  end

  def destroy
    if @card.destroy
      redirect_to admin_cards_path
    end
  end

  private
  def get_card
    @card = Card.where(identifier: params[:id]).first
  end
  def card_param
    params.require(:card).permit :title, :description, :price, :image
  end
end

app/helpers/admin/cards_helper.rb
module Admin::CardsHelper
end

app/views/admin/cards/_admin_panel.html.slim
= link_to "edit", edit_admin_card_path( card )
= link_to "delete", admin_card_path( card ) , method: :delete

app/views/admin/cards/_form.html.slim
= simple_form_for [:admin, @card] do |f|
  = f.input :title
  = f.input :description, as: :text
  = f.input :price, as: :integer,input_html: { min: 0 }, label: "Price in cents!!!"
  = f.input :image, label: "Card image: "
  = f.submit

app/views/admin/cards/edit.html.slim
section.admin
  = render 'form'

app/views/admin/cards/index.html.slim
section.cards
  
  ul
    - @cards.each do |card|
      li
        = image_tag card.image.url
        h3 
          = card.title
        = button_to "[edit]", edit_admin_card_path(card), method: :get
        = button_to "[delete]", admin_card_path(card),class: 'destroy', method: :delete
    li.new
      = link_to 'ADD CARDS', new_admin_card_path

app/views/admin/cards/new.html.slim
section.admin style="top: 250px;"
  = render 'form'